// Generated by Saber 0.1.0

// swiftlint:disable all

import Foundation

internal class AppContainer: AppContaining {

    internal init() {
    }

    internal var foo: Foo {
        let foo = self.makeFoo()
        return foo
    }

    internal var bar: Bar {
        let bar = self.makeBar()
        self.injectTo(bar: bar)
        return bar
    }

    private func makeFoo() -> Foo {
        return Foo()
    }

    private func makeBar() -> Bar {
        return Bar(foo: { [unowned self] in return self.foo })
    }

    private func injectTo(bar: Bar) {
        bar.makeFoo = { [unowned self] in return self.foo }
        bar.set(fooFactory: { [unowned self] in return self.foo })
    }

}